[application]
name = "Tailcode"
version = "1.0.0"
descriptions = "Show Tailscale connection info and QR code for the KVM web UI."

[author]
name = "cleavines01"

[interaction]
requires_user_input = false
